/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { ReservationBookingListRelationFilter } from "../../reservationBooking/base/ReservationBookingListRelationFilter";
import { SeatingListRelationFilter } from "../../seating/base/SeatingListRelationFilter";
import { TableListRelationFilter } from "../../table/base/TableListRelationFilter";

@InputType()
class RestaurantWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  address?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  phoneNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ReservationBookingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReservationBookingListRelationFilter)
  @IsOptional()
  @Field(() => ReservationBookingListRelationFilter, {
    nullable: true,
  })
  reservationBookings?: ReservationBookingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SeatingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SeatingListRelationFilter)
  @IsOptional()
  @Field(() => SeatingListRelationFilter, {
    nullable: true,
  })
  seatings?: SeatingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TableListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TableListRelationFilter)
  @IsOptional()
  @Field(() => TableListRelationFilter, {
    nullable: true,
  })
  tables?: TableListRelationFilter;
}

export { RestaurantWhereInput as RestaurantWhereInput };
