/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  WeeklyOpeningHours as PrismaWeeklyOpeningHours,
} from "@prisma/client";

export class WeeklyOpeningHoursServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WeeklyOpeningHoursCountArgs, "select">
  ): Promise<number> {
    return this.prisma.weeklyOpeningHours.count(args);
  }

  async weeklyOpeningHoursItems(
    args: Prisma.WeeklyOpeningHoursFindManyArgs
  ): Promise<PrismaWeeklyOpeningHours[]> {
    return this.prisma.weeklyOpeningHours.findMany(args);
  }
  async weeklyOpeningHours(
    args: Prisma.WeeklyOpeningHoursFindUniqueArgs
  ): Promise<PrismaWeeklyOpeningHours | null> {
    return this.prisma.weeklyOpeningHours.findUnique(args);
  }
  async createWeeklyOpeningHours(
    args: Prisma.WeeklyOpeningHoursCreateArgs
  ): Promise<PrismaWeeklyOpeningHours> {
    return this.prisma.weeklyOpeningHours.create(args);
  }
  async updateWeeklyOpeningHours(
    args: Prisma.WeeklyOpeningHoursUpdateArgs
  ): Promise<PrismaWeeklyOpeningHours> {
    return this.prisma.weeklyOpeningHours.update(args);
  }
  async deleteWeeklyOpeningHours(
    args: Prisma.WeeklyOpeningHoursDeleteArgs
  ): Promise<PrismaWeeklyOpeningHours> {
    return this.prisma.weeklyOpeningHours.delete(args);
  }
}
