/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TableGroup } from "./TableGroup";
import { TableGroupCountArgs } from "./TableGroupCountArgs";
import { TableGroupFindManyArgs } from "./TableGroupFindManyArgs";
import { TableGroupFindUniqueArgs } from "./TableGroupFindUniqueArgs";
import { DeleteTableGroupArgs } from "./DeleteTableGroupArgs";
import { TableGroupService } from "../tableGroup.service";
@graphql.Resolver(() => TableGroup)
export class TableGroupResolverBase {
  constructor(protected readonly service: TableGroupService) {}

  async _tableGroupsMeta(
    @graphql.Args() args: TableGroupCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TableGroup])
  async tableGroups(
    @graphql.Args() args: TableGroupFindManyArgs
  ): Promise<TableGroup[]> {
    return this.service.tableGroups(args);
  }

  @graphql.Query(() => TableGroup, { nullable: true })
  async tableGroup(
    @graphql.Args() args: TableGroupFindUniqueArgs
  ): Promise<TableGroup | null> {
    const result = await this.service.tableGroup(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TableGroup)
  async deleteTableGroup(
    @graphql.Args() args: DeleteTableGroupArgs
  ): Promise<TableGroup | null> {
    try {
      return await this.service.deleteTableGroup(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
